### ISSUE TITLE
practica_Architect-IrvingFernandoReyesPacheco

### ISSUE THREAD

**Issue by IrvingFernand0** [SistemasTecTlaxiaco/actividad-3-practica-architect-IrvingFernand0#1]
[Practica Architect.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-practica-architect-IrvingFernand0/files/9486733/Practica.Architect.pdf)

**Comment by NoeliaGlez** [comment]
19.4% el nombre del docente esta mal

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
